### ISSUE TITLE
⚡️ Update `GoldHEN` + 📝 Document `goldhen.bin` to `goldhen.h` conversion

### ISSUE THREAD

**Issue by Rikj000** [stooged/PS4-Server-900#2]
Hello @stooged,
first of all thanks a lot for this project!
So far it has worked quite well for me :slightly_smiling_face: 

## Issue Description
- [x] ⚡️ Update included [`goldhen.h`](https://github.com/stooged/PS4-Server-900/blob/main/PS4_Server_900/goldhen.h) file with the latest [`goldhen.bin`](https://github.com/GoldHEN/GoldHEN),   
    at the moment of writing this is `v2.2.4`
- [x] 📝 Document the [`goldhen.bin`](https://github.com/GoldHEN/GoldHEN) to [`goldhen.h`](https://github.com/stooged/PS4-Server-900/blob/main/PS4_Server_900/goldhen.h) conversion.   
    In my experience, I've gotten the best results with using the included [`goldhen.h`](https://github.com/stooged/PS4-Server-900/blob/main/PS4_Server_900/goldhen.h) instead of the official [`goldhen.bin`](https://github.com/GoldHEN/GoldHEN)!   
    
    For this reason I think it would be nice to have the conversion process documented, then it would be:   
    - Easier for the community to submit GoldHEN update PRs as new versions come out
    - Reduce your work-load in maintaining this project (due to more PRs)

**Comment by stooged** [comment]
i mush have forgotten to push the goldhen.h file for this repo, it is the same as the [900u](https://github.com/stooged/PS4-Server-900u) repo as the two were merged into the same code.
i have updated the golden.h file for this repo.


as for documenting the goldhen .bin to .h the python source code and binary for that are in the bin2h folder of the repo

https://github.com/stooged/PS4-Server-900/tree/main/bin2h


this is the py code

```

#!/usr/bin/python3
import os
import sys
import gzip
try:filename = sys.argv[1]
except:sys.exit(".bin file required\n\nExample: bin2h goldhen.bin")
f = open(filename, 'rb')
bindat = f.read()
f.close()
f = gzip.open("goldhen.bin.gz", 'wb')
f.write(bindat)
f.close()
cnt = 0
filename = os.path.basename(filename).replace('.bin', '')
tmpdat = "#if INTHEN\n#define INTHEN_NAME \"" + filename + "\"\nstatic const uint8_t goldhen_gz[] PROGMEM = {\n"
with open("goldhen.bin.gz", 'rb') as f:
    chnk = f.read(1)
    while chnk:
        if cnt == 31:
            cnt = 0
            tmpdat = tmpdat + "%s,\n" % ord(chnk)
        else:    
            tmpdat = tmpdat + "%s, " % ord(chnk)
        cnt=cnt+1
        chnk = f.read(1)
if tmpdat.endswith(","):
  tmpdat = tmpdat[:-1]
elif tmpdat.endswith(", "):
  tmpdat = tmpdat[:-2]
elif tmpdat.endswith(",\n"):
  tmpdat = tmpdat[:-2]
tmpdat = tmpdat + "\n};\n#endif"
f.close()
if os.path.exists("goldhen.h"):
  os.remove("goldhen.h")
f = open("goldhen.h", 'w+', encoding="utf-8") 
f.write(tmpdat)
f.close()
if os.path.exists("goldhen.bin.gz"):
  os.remove("goldhen.bin.gz")

```

**Comment by Rikj000** [comment]
Thanks a lot! 😊

**Comment by doody111431-eng** [comment]
عربي
